# Generated by Django 5.0.2 on 2024-04-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_rename_is_favorite_product_is_favorite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_Favorite',
            new_name='is_favorite',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_Featured',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_New',
            new_name='is_new',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_Popular',
            new_name='is_popular',
        ),
    ]
