# Generated by Django 5.0.2 on 2024-04-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_product_description1_product_description2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
