# Generated by Django 5.0.2 on 2024-04-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='ttile',
            new_name='title',
        ),
    ]
